<?php
use Doctrine\ORM\EntityRepository;

namespace AppBundle\Repository;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOneByContact($contact)
    {
    	
     return $this->findByContact($contact); 
     
    }

    public function remove($id)
    {
     $em = $this->getEntityManager();	
     $subscription =  $this->find($id); 
     if(!empty($subscription))
     {
        $em->remove($subscription);
        $em->flush();
     }
     
     return $subscription;
     
    }


}
